GET http://localhost:5000/messages

###
PUT http://localhost:5000/messages/7a24f931-08ee-4347-b0c6-34c6498c72c7
Content-Type: application/json

{
  "text": "What? It is something new... It`s updating or creating)!",
  "eMail": "AllenaLinkedIn@gmail.com.ua",
  "timeValue": "01.01.2015"
}

###
DELETE http://localhost:5000/messages/34e0549c-4ab4-449a-8604-e367ce69cf13

###
POST http://localhost:5000/messages
Content-Type: application/json

{
  "text": "Hi guys! How are you?",
  "eMail": "awrttttasddfff@gmail.com",
  "timeValue": "30.03.2017"
}

